import 'cypress-iframe';
import 'cypress-file-upload'
describe('Azure Active Directory Authentication', () => {
beforeEach(() => {
    cy.loginToAAD(Cypress.env('aad_username'), Cypress.env('aad_password'))
    cy.visit('https://apps.powerapps.com/play/e/e9e91046-cda3-e38d-bd94-7a6db9f8e8f3/a/24d8b2bc-b9a6-4ace-b062-49a7cd73f9bc?tenantId=26422a3a-c74b-4d07-9e29-8d6ecf66fa8d&source=portal')
    cy.wait(38000)
    })
it('verifies the Length & Clear button', () => {
    cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find('#publishedCanvas > div > div.screen-animation.animated > div > div > div:nth-child(2) > div > div > div > div > div').should('have.text','Invoice Uploader')
    cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).title().should('eq','PROAP-Invoice Uploader - PowerApps')
    cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find('#publishedCanvas > div > div.screen-animation.animated > div > div > div:nth-child(7)').click()
    cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find('div[class="item11 appmagic-dropdownListItem"]').click()
    cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find('#publishedCanvas > div > div.screen-animation.animated > div > div > div:nth-child(9)').click()
    cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).contains('Battery').click()
    cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find('#publishedCanvas > div > div.screen-animation.animated > div > div > div:nth-child(13)').type(" ARMOR SAS")
    cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find('div[class="itemTemplateContainer_1wcmb2a"]').click()
    cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find('input[appmagic-control="txtInvoiceNumbertextbox"]').type('ANANDA 1234587ADCHFBHJHJFJHFHJ').invoke('val').should('not.have.lengthOf', 20)
    cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find('div[data-control-id="27"]').click()
    cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find('td[data-day="2"]').click()
    cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find('button[class="appmagic-datepicker-ok-button"]').click()
    cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find('div[data-control-id="29"]').click()
    cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).contains('BROKERAGE').click()
    cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find('input[class="addFileInput_1xqaqtd-o_O-addFileInput_3hmsj"]').attachFile('My finding.docx')
    cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find('input[appmagic-control="txtContactReferencetextbox"]').type('APP-12461-01ANANDA MOHAN MALLIPUDI DONE THE JOB').invoke('val').should('not.have.lengthOf', 255)
    cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find('#publishedCanvas > div > div.screen-animation.animated > div.canvasContentDiv.container_gfluoe.activeScreen > div > div:nth-child(32) > div > div > div > div > button > div > div').click().wait(6000)
})
it('verifies the Length & SUBMIT button', () => {
    cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find('#publishedCanvas > div > div.screen-animation.animated > div > div > div:nth-child(2) > div > div > div > div > div').should('have.text','Invoice Uploader')
    cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).title().should('eq','PROAP-Invoice Uploader - PowerApps')
     cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find('#publishedCanvas > div > div.screen-animation.animated > div > div > div:nth-child(7)').click()
     cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find('div[class="item11 appmagic-dropdownListItem"]').click()
     cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find('#publishedCanvas > div > div.screen-animation.animated > div > div > div:nth-child(9)').click()
     cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).contains('Battery').click()
     cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find('#publishedCanvas > div > div.screen-animation.animated > div > div > div:nth-child(13)').type(" ARMOR SAS")
     cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find('div[class="itemTemplateContainer_1wcmb2a"]').click()
     cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find('input[appmagic-control="txtInvoiceNumbertextbox"]').type('ANANDA 1234587ADCHFBHJHJFJHFHJ').invoke('val').should('not.have.lengthOf', 20)
     cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find('div[data-control-id="27"]').click()
     cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find('td[data-day="2"]').click()
     cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find('button[class="appmagic-datepicker-ok-button"]').click()
     cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find('div[data-control-id="29"]').click()
     cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).contains('BROKERAGE').click()
     cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find('input[class="addFileInput_1xqaqtd-o_O-addFileInput_3hmsj"]').attachFile('My finding.docx')
     cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find('input[appmagic-control="txtContactReferencetextbox"]').type('APP-12461-01ANANDA MOHAN MALLIPUDI DONE THE JOB').invoke('val').should('not.have.lengthOf', 255)
     cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find(' #publishedCanvas > div > div.screen-animation.animated > div.canvasContentDiv.container_gfluoe.activeScreen > div > div:nth-child(31) > div > div > div > div > button > div').click().wait(6000)
     cy.get('#fullscreen-app-host').its('0.contentDocument.body').then(cy.wrap).find('#publishedCanvas > div > div.screen-animation.animated > div > div > div:nth-child(36) > div > div > div > div > div').should('have.text','Invoice has been saved successfully.')
    })
})

